language: node_js

node_js:
  - "10.7.0"

services:
  - postgresql

before_script:
  - psql -c 'create database mydiary;' -U postgres

cache:
  directories:
    - "node_modules"

# https://stackoverflow.com/questions/40802732/travisci-failing-on-node-bcrypt-with-node-gyp-errors
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    
after_success: npm run coverage