swagger: "2.0"
info:
  description: "MyDiary is an online journal where users can pen down their thoughts and feelings"
  version: "1.0.0"
  title: "MyDiary"
  termsOfService: ""
  contact:
    email: "sola.dav7@gmail.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "my-diary-api.herokuapp.com"
basePath: "/api/v1"

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    
tags:
- name: "Authentication"
  description: "Endpoints for authentication"
- name: "Entries"
  description: "Operations for entries"
- name: "User"
  description: "Operations for user information"
  
schemes:
- "https"

paths:
  /auth/signup:
    post:
      tags:
      - "Authentication"
      summary: "Create a new user account"
      description: "This endpoint enables the user to create a new user account"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "formData"
        name: "email"
        description: "Email address of the user"
        required: true
        type: string
      - in: "formData"
        name: "password"
        description: "Desired Password. Must not contain spaces and must be be at least 5 characters long"
        required: true
        type: string
      responses:
        201:
          description: "Successful signup"
          examples:
            application/json:
              token: eyERTciergyzIBr1NiwerIdssdeyR5csdfs.LCJleHAiOjE1MjI0MDM3MTR9.piPT-ut9xAg8wYUvC-PgrER45iyyuERR
        409:
          description: "User already exists"
          examples:
            application/json:
              error:
                message:
                  "User already exists. Please log in"
        400:
          description: "Bad request. Invalid credentials or data"
          examples:
            application/json:
              error:
                  - param: email
                    message: Your email is invalid
                  - param: password
                    message: Your password should contain minimum of 5 characters
        500:
          description: "Server Error"
          examples:
            application/json:
              error:
                message: An error occurred on the server
  /auth/login:
    post:
      tags:
      - "Authentication"
      summary: "Logs in existing user and returns a token"
      description: "This endpoint enables the user to login"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "formData"
        name: "email"
        description: "Email address of the user"
        required: true
        type: string
      - in: "formData"
        name: "password"
        description: "Desired Password. Must not contain spaces and must be be at least 5 characters long"
        required: true
        type: string
      responses:
        200:
          description: "Successful login"
          examples:
            application/json:
              token: eyERTciergyzIBr1NiwerIdssdeyR5csdfs.LCJleHAiOjE1MjI0MDM3MTR9.piPT-ut9xAg8wYUvC-PgrER45iyyuERR
        422:
          description: "Incorrect user credentials"
          examples:
            application/json:
              error:
                message:
                  "Your email or password is invalid"
        400:
          description: "Bad request. Invalid credentials or data"
          examples:
            application/json:
              error:
                  - param: email
                    message: Your email is invalid
                  - param: password
                    message: Your password should contain minimum of 5 characters
        500:
          description: "Server Error"
          examples:
            application/json:
              error:
                message: An error occurred on the server
  
  /profile:
    get:
      tags:
      - "User"
      summary: "User Profile info"
      description: "This endpoint returns the user's basic profile info"
      produces:
      - "application/json"
      security:
      -  Bearer: []
      responses:
        200:
          description: "Successful fetched user info"
          examples:
            application/json:
              email: john.dave@gmail.com
              entries_count: 35
              fav_count: 8
              created_on: '2018-08-17T23:58:13.698Z'
              push_sub: {}
              reminder_set: true
        401:
          description: "Authorization error"
          examples:
            application/json:
              error:
                message:
                  "Authorization failed. Please provide a token"
        500:
          description: "Server Error"
          examples:
            application/json:
              error:
                message: An error occurred on the server
    put:
      tags:
      - "User"
      summary: "Update user profile and preferences"
      description: "This endpoint updates the user's profile amd sets their reminder preferences"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "formData"
        name: "push_sub"
        description: "The push subscription object"
        required: false
        type: string
      - in: "formData"
        name: "reminder_set"
        description: "Boolean indicating whether reminder is set or not"
        required: false
        type: string
      security:
      -  Bearer: []
      responses:
        204:
          description: "Successfully updated user profile"
          examples:
            application/json:
              No content
        400:
          description: "Bad request. Invalid credentials or data"
          examples:
            application/json:
              error:
                  - param: push_sub
                    message: Push Subscription should be JSON
                  - param: reminder_set
                    message: Reminder preference should be boolean
        401:
          description: "Authorization error"
          examples:
            application/json:
              error:
                message:
                  "Authorization failed. Please provide a token"
        500:
          description: "Server Error"
          examples:
            application/json:
              error:
                message: An error occurred on the server
  /entries:
    get:
      tags:
      - "Entries"
      summary: "Retrieves all user entries"
      description: "This endpoint returns an object of user entries and related meta information"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "filter"
        description: "The entries that have a particular property which is the value of the filter"
        required: false
        type: string
      - in: "query"
        name: "limit"
        description: "The maximum number of entries to return for each request"
        required: false
        type: string
      - in: "query"
        name: "page"
        description: "The page of entries to return when limit is applied"
        required: false
        type: string
      security:
      -  Bearer: []
      responses:
        200:
          description: "Successfully fetched all entries"
          examples:
            application/json:
              entries:
              - id: 14
                title: 'My last days at Google'
                content: 'It was an eventful summer. A week characterized by the nuances of IO conference...'
                is_favorite: true
                updated_on: '2018-08-02T10:33:49.297Z'
                created_on: '2018-08-02T10:33:49.297Z'
              - id: 23
                title: 'Tough times make tough people'
                content: 'Mental and character growth is definitely one of the most painful growth experiences in human life...'
                is_favorite: false
                updated_on: '2018-08-02T10:33:49.297Z'
                created_on: '2018-08-02T10:33:49.297Z'
              meta:
                limit: 20
                page: 0
                count: 2
        401:
          description: "Authorization error"
          examples:
            application/json:
              error:
                message:
                  "Authorization failed. Please provide a token"
        500:
          description: "Server Error"
          examples:
            application/json:
              error:
                message: An error occurred on the server
    post:
      tags:
      - "Entries"
      summary: "Adds a new user entry"
      description: "This endpoint adds a new user entry and returns the newly added entry"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "formData"
        name: "title"
        description: "The title of the entry"
        required: true
        type: string
      - in: "formData"
        name: "content"
        description: "The content of the entry"
        required: true
        type: string
      - in: "formData"
        name: "is_favorite"
        description: "Boolean value that shows if entry is marked as favorite"
        required: true
        type: boolean
      security:
      -  Bearer: []
      responses:
        201:
          description: "Successfully created entry"
          examples:
            application/json:
              id: 14
              title: 'My last days at Google'
              content: 'It was an eventful summer. A week characterized by the nuances of IO conference...'
              is_favorite: true
              created_on: '2018-08-02T10:33:49.297Z'
        401:
          description: "Authorization error"
          examples:
            application/json:
              error:
                message:
                  "Authorization failed. Please provide a token"
        400:
          description: "Bad request. Invalid credentials or data"
          examples:
            application/json:
              error:
                  - param: title
                    message: Title should not be empty
                  - param: content
                    message: Content should not be empty
        500:
          description: "Server Error"
          examples:
            application/json:
              error:
                message: An error occurred on the server
  /entries/{id}:
    get:
      tags:
      - "Entries"
      summary: "Get entry by id"
      description: "This endpoint retrieves a single user entry by id"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      security:
      -  Bearer: []
      responses:
        200:
          description: "Successfully fetched single entry"
          examples:
            application/json:
              id: 14
              title: 'My last days at Google'
              content: 'It was an eventful summer. A week characterized by the nuances of IO conference...'
              is_favorite: true
              created_on: '2018-08-02T10:33:49.297Z'
        401:
          description: "Authorization error"
          examples:
            application/json:
              error:
                message:
                  "Authorization failed. Please provide a token"
        404:
          description: "Resource not found"
          examples:
            application/json:
              error:
                message:
                  "Entry not found"
        500:
          description: "Server Error"
          examples:
            application/json:
              error:
                message: An error occurred on the server
    put:
      tags:
      - "Entries"
      summary: "Modify entry by id"
      description: "This endpoint modifies a single user entry by id not later than 24 hours after it was created"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      - in: "formData"
        name: "title"
        description: "The title of the entry"
        required: false
        type: string
      - in: "formData"
        name: "content"
        description: "The content of the entry"
        required: false
        type: string
      - in: "formData"
        name: "is_favorite"
        description: "Boolean value that shows if entry is marked as favorite"
        required: false
        type: boolean
      security:
      -  Bearer: []
      responses:
        200:
          description: "Successfully modified single entry"
          examples:
            application/json:
              id: 14
              title: 'My last days at Microsoft'
              content: 'It was an eventful summer. A week characterized by the nuances of IO conference...'
              is_favorite: true
              created_on: '2018-08-02T10:33:49.297Z'
        400:
          description: "Bad request. Invalid credentials or data"
          examples:
            application/json:
              error:
                  - param: title
                    message: Title should not be empty
                  - param: content
                    message: Content should not be empty
        401:
          description: "Authorization error"
          examples:
            application/json:
              error:
                message:
                  "Authorization failed. Please provide a token"
        403:
          description: "Cannot update entry 24 hours or more after it was created"
          examples:
            application/json:
              error:
                message:
                  "Cannot update entry after 24 hours"
        500:
          description: "Server Error"
          examples:
            application/json:
              error:
                message: An error occurred on the server
                    
    delete:
      tags:
      - "Entries"
      summary: "Delete entry by id"
      description: "This endpoint deletes a single user entry by id"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      security:
      -  Bearer: []
      responses:
        204:
          description: "Successfully deleted single entry"
        401:
          description: "Authorization error"
          examples:
            application/json:
              error:
                message:
                  "Authorization failed. Please provide a token"
        404:
          description: "Resource not found"
          examples:
            application/json:
              error:
                message:
                  "Entry not found"
        500:
          description: "Server Error"
          examples:
            application/json:
              error:
                message: An error occurred on the server